- koji_cli_plugins/kojismokydingo.py
> Allow entry_point cli commands to return None

- README.md
- koji-smoky-dingo.spec
- koji_cli_plugins/kojismokydingo.py
- setup-meta.py
> spec for building as an RPM using the Fedora packaging guidelines

- README.md
- koji_cli_plugins/kojismokydingometa.py
- kojismokydingo/__init__.py
- kojismokydingo/renum_tag.py
- kojismokydingo/swap_inheritance.py
- setup.py
> Work with refactored koji 1.18 permissions

- kojismokydingo/userinfo.py
> work with older and new getUser calls. fixes #15

- kojismokydingo/cli/__init__.py
> explicitly set field index in tabulate format string

- kojismokydingo/cli/hosts.py
- kojismokydingo/common.py
- kojismokydingo/hosts.py
- tests/common.py
- adds a new parse_datetime function to kojismokydingo.common
- fixes Issue #36
> fix for datetime parsing in check-hosts

- README.md
- docs/commands.rst
- docs/commands/block-env-var.rst
- docs/commands/block-rpm-macro.rst
- docs/commands/list-tag-extras.rst
- docs/commands/remove-env-var.rst
- docs/commands/remove-rpm-macro.rst
- docs/commands/set-env-var.rst
- docs/commands/set-rpm-macro.rst
- docs/commands/unset-env-var.rst
- docs/commands/unset-rpm-macro.rst
- docs/conf.py
- docs/overview.rst
- kojismokydingo.spec
- kojismokydingo/cli/tags.py
- setup.py
- tests/cli/__init__.py
- tests/packaging.sh
adds a docs subpackage which bundles the html docs and man pages
Closes #52
> optional docs subpackage

- docs/commands/bulk-tag-builds.rst
- kojismokydingo/cli/builds.py
- kojismokydingo/tags.py
- adds the --create option
- add kojismokydingo.tags.ensure_tag function
- update docs
- Closes #49
> add --create option to bulk-tag-builds

- docs/commands/latest-archives.rst
- docs/commands/list-build-archives.rst
- kojismokydingo/archives.py
- kojismokydingo/builds.py
- kojismokydingo/cli/archives.py
- setup.cfg
> Enable filtering of archives by architecture

- README.md
- docs/commands.rst
- docs/commands/open.rst
- docs/overview.rst
- docs/release_notes/v0.9.6.rst
- kojismokydingo.spec
- kojismokydingo/__init__.py
- kojismokydingo/cli/clients.py
- setup.py
- tests/cli/__init__.py
Implements a new command `koji open`  Closes #65
> New 'koji open' command

- README.md
- docs/commands.rst
- docs/commands/bulk-move-builds.rst
- docs/commands/bulk-tag-builds.rst
- docs/commands/bulk-untag-builds.rst
- docs/faq.rst
- docs/overview.rst
- docs/release_notes/v0.9.7.rst
- kojismokydingo/builds.py
- kojismokydingo/cli/builds.py
- kojismokydingo/cli/clients.py
- kojismokydingo/sift/__init__.py
- setup.py
- tests/cli/__init__.py
- tests/common.py
- tests/packaging.sh
- tools/Containerfile.fedora34
Adds two new commands and the relevant documentation
* bulk-move-builds
* bulk-untag-builds
Closes #74
> new commands bulk-move-builds and bulk-untag-builds 

- README.md
- docs/overview.rst
- docs/release_notes.rst
- docs/release_notes/v1.0.0.rst
- koji_cli_plugins/kojismokydingometa.py
- kojismokydingo.spec
- kojismokydingo/__init__.py
- kojismokydingo/archives.py
- kojismokydingo/builds.py
- kojismokydingo/cli/archives.py
- kojismokydingo/cli/builds.py
- kojismokydingo/common.py
- kojismokydingo/sift/builds.py
- setup.cfg
- setup.py
- tests/archives.py
- tests/builds.py
- tests/sift/builds.py
- tools/Containerfile.fedora28
- tools/common.sh
- tools/launch-build.sh
- tools/launch-test.sh
- tools/rpmbuild.sh
> version 1.0.0

- README.md
Signed-off-by: arewm <arewm@users.noreply.github.com>
> abstract python version

- kojismokydingo/cli/builds.py
> backport of no_pkg_owner to KSD 1 stream

- docs/siftylang.rst
- kojismokydingo/builds.py
- kojismokydingo/sift/builds.py
- tests/sift/builds.py
> evr-high evr-low build sieves

- docs/release_notes.rst
- docs/release_notes/v1.1.0.rst
- docs/siftylang.rst
- kojismokydingo.spec
- kojismokydingo/builds.py
- kojismokydingo/sift/builds.py
- setup.cfg
- setup.py
- tests/sift/builds.py
> 1.1 evr sieve

- Makefile
- kojismokydingo/cli/clients.py
- kojismokydingo/sift/parse.py
- setup.cfg
bandit https://github.com/PyCQA/bandit
* add a bandit tox test
* add a bandit Makefile target
* inject bandit configuration into setup.cfg
*silence invalid issues
> use bandit for some security-ish scanning

- kojismokydingo/__init__.py
Closes issue #103 
`ManagedClientSession.logger` is now a property, which will create a basic logging configuration when accessed.
> make client session loggers into a property

- kojismokydingo/types.py
- stubs/koji/__init__.pyi
> more stubs

- docs/commands/userinfo.rst
- docs/release_notes/v2.0.0.rst
- kojismokydingo/cli/users.py
- kojismokydingo/types.py
- kojismokydingo/users.py
- tests/cli/users.py
> added --stats option to userinfo command

- kojismokydingo.spec
- tools/Containerfile.centosstream9
- tools/Containerfile.fedora37
- tools/Containerfile.fedora38
drop fedora35. add fedora37, fedora38, and centosstream9
> update rpm container builds

- docs/conf.py
- docs/faq.rst
- docs/index.rst
- docs/kojismokydingo.rst
- docs/kojismokydingo/rpms.rst
- docs/pluginconfig.rst
- docs/release_notes.rst
- docs/release_notes/v1.1.0.rst
- docs/release_notes/v2.0.0.rst
- kojismokydingo.spec
- kojismokydingo/users.py
> Docs plugin conf

- Makefile
- README.md
- docs/commands/check-repo.rst
- docs/overview.rst
- docs/release_notes/v2.0.0.rst
- kojismokydingo.spec
- setup.cfg
> prep for v2.0.0

- kojismokydingo/types.py
- stubs/koji/__init__.pyi
Not sure if you want these types here or in types.py
> update stubs for listTasks

- .github/workflows/tox.yml
- setup.cfg
- stubs/koji/__init__.pyi
> Enable GitHub Actions

- docs/commands/affected-targets.rst
- docs/release_notes/v2.1.0.rst
- kojismokydingo/cli/__init__.py
- kojismokydingo/cli/builds.py
- kojismokydingo/cli/tags.py
- kojismokydingo/common.py
- kojismokydingo/tags.py
> Fix `gather_affected_targets`

- koji_cli_plugins/kojismokydingometa.py
- kojismokydingo/cli/__init__.py
- kojismokydingo/types.py
type definition for the koji cli command handler fn
> Callable annotate

- .github/workflows/build_docs.yml
- .github/workflows/build_rpms.yml
- .github/workflows/build_wheel.yml
- .github/workflows/on_nightly.yml
- .github/workflows/on_release.yml
- .github/workflows/run_bandit.yml
- .github/workflows/run_tests.yml
> updated action versions

- .github/workflows/build_rpms.yml
- tools/Containerfile.fedora39
- tools/Containerfile.fedora40
- tools/common.sh
> enable fedora 39,40 and disable fedora 36,37
